version: "3.9"
services:
  caddy:
    build: caddy
    ports:
      - "2016:2016"
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/conf/Caddyfile:/data/caddy/conf/Caddyfile
      - ./caddy/uploads:/data/caddy/uploads
